# Generated by Django 5.2.7 on 2025-10-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverification',
            name='email_verif_user_em_e6527e_idx',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=False),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='otp_code',
            field=models.CharField(db_column='otp_code', max_length=6),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user_email',
            field=models.CharField(db_column='user_email', max_length=100),
        ),
        migrations.AlterModelTable(
            name='emailverification',
            table='emailverification',
        ),
    ]
