# Generated by Django 5.2.7 on 2025-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_emailverification_email_verif_user_em_e6527e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='diagnostictest',
            options={'ordering': ['test_name']},
        ),
        migrations.AlterModelOptions(
            name='emailverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AlterModelOptions(
            name='therapistdirectory',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
