# Generated by Django 5.2.7 on 2025-11-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_admin_options_alter_diagnostictest_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                DROP TABLE IF EXISTS message CASCADE;
                DROP TABLE IF EXISTS summary CASCADE;
                DROP TABLE IF EXISTS testresult CASCADE;
                DROP TABLE IF EXISTS session CASCADE;
                DROP TABLE IF EXISTS diagnostictest CASCADE;
                DROP TABLE IF EXISTS therapistdirectory CASCADE;
                DROP TABLE IF EXISTS admin CASCADE;
                DROP TABLE IF EXISTS "user" CASCADE;

                CREATE TABLE "user" (
                    user_id SERIAL PRIMARY KEY,
                    email VARCHAR(100) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    first_name VARCHAR(100) NOT NULL,
                    last_name VARCHAR(100),
                    dob DATE NOT NULL,
                    gender VARCHAR(6) NOT NULL DEFAULT 'Other',
                    lang_pref VARCHAR(7) NOT NULL DEFAULT 'English',
                    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                );

                CREATE TABLE admin (
                    admin_id SERIAL PRIMARY KEY,
                    email VARCHAR(100) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    first_name VARCHAR(100) NOT NULL,
                    last_name VARCHAR(100),
                    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                    last_login TIMESTAMPTZ
                );

                CREATE TABLE diagnostictest (
                    test_id SERIAL PRIMARY KEY,
                    test_code VARCHAR(50) NOT NULL,
                    test_name VARCHAR(100) NOT NULL,
                    questions TEXT NOT NULL
                );

                CREATE TABLE session (
                    session_id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
                    session_type VARCHAR(5) NOT NULL DEFAULT 'text',
                    emotional_tone VARCHAR(50),
                    started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                    ended_at TIMESTAMPTZ
                );
                CREATE INDEX IF NOT EXISTS session_user_id_idx ON session(user_id);

                CREATE TABLE message (
                    message_id SERIAL PRIMARY KEY,
                    session_id INTEGER NOT NULL REFERENCES session(session_id) ON DELETE CASCADE,
                    sender VARCHAR(4) NOT NULL,
                    content_type VARCHAR(5) NOT NULL DEFAULT 'text',
                    message_text TEXT,
                    audio_file_path VARCHAR(255)
                );
                CREATE INDEX IF NOT EXISTS message_session_id_idx ON message(session_id);

                CREATE TABLE summary (
                    summary_id SERIAL PRIMARY KEY,
                    session_id INTEGER NOT NULL REFERENCES session(session_id) ON DELETE CASCADE,
                    keypoints TEXT NOT NULL,
                    generated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                );
                CREATE INDEX IF NOT EXISTS summary_session_id_idx ON summary(session_id);

                CREATE TABLE therapistdirectory (
                    therapist_id SERIAL PRIMARY KEY,
                    first_name VARCHAR(100) NOT NULL,
                    last_name VARCHAR(100),
                    phone_number VARCHAR(20),
                    address VARCHAR(255),
                    city VARCHAR(100)
                );

                CREATE TABLE testresult (
                    result_id SERIAL PRIMARY KEY,
                    test_id INTEGER NOT NULL REFERENCES diagnostictest(test_id) ON DELETE CASCADE,
                    user_id INTEGER NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
                    score INTEGER NOT NULL,
                    severity_level VARCHAR(20) NOT NULL DEFAULT 'minimal',
                    taken_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                    user_responses VARCHAR(50)
                );
                CREATE INDEX IF NOT EXISTS testresult_user_id_idx ON testresult(user_id);
                CREATE INDEX IF NOT EXISTS testresult_test_id_idx ON testresult(test_id);
            ''',
            reverse_sql='''
                DROP TABLE IF EXISTS message CASCADE;
                DROP TABLE IF EXISTS summary CASCADE;
                DROP TABLE IF EXISTS testresult CASCADE;
                DROP TABLE IF EXISTS session CASCADE;
                DROP TABLE IF EXISTS diagnostictest CASCADE;
                DROP TABLE IF EXISTS therapistdirectory CASCADE;
                DROP TABLE IF EXISTS admin CASCADE;
                DROP TABLE IF EXISTS "user" CASCADE;
            ''',
        ),
    ]
