# Generated by Django 5.2.7 on 2025-11-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_create_app_tables_postgres'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "user" ADD COLUMN IF NOT EXISTS city VARCHAR(100);',
                    reverse_sql='ALTER TABLE "user" DROP COLUMN IF EXISTS city;',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "user" ADD COLUMN IF NOT EXISTS nearest_major_city VARCHAR(20);',
                    reverse_sql='ALTER TABLE "user" DROP COLUMN IF EXISTS nearest_major_city;',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='city',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='user',
                    name='nearest_major_city',
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ('Islamabad', 'Islamabad'),
                            ('Lahore', 'Lahore'),
                            ('Karachi', 'Karachi'),
                            ('Multan', 'Multan'),
                            ('Peshawar', 'Peshawar'),
                            ('Faisalabad', 'Faisalabad'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name='user',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True),
                ),
                migrations.AlterField(
                    model_name='user',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
    ]
