# Generated by Django 5.2.7 on 2025-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_location_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "user" ALTER COLUMN nearest_major_city TYPE VARCHAR(100);',
                    reverse_sql='ALTER TABLE "user" ALTER COLUMN nearest_major_city TYPE VARCHAR(20);',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='nearest_major_city',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
