# Generated by Django 5.2.7 on 2025-11-11 18:36

import uuid

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expand_major_city_field'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='message',
                    name='session',
                    field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='messages', to='api.session'),
                ),
                migrations.AddField(
                    model_name='summary',
                    name='session',
                    field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='summaries', to='api.session'),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='emotional_tone',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_type',
        ),
        migrations.AddField(
            model_name='session',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='continuation_context',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='full_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='session_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='short_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('full', 'Full Transcript'), ('pending_archive', 'Pending Archive'), ('summary_only', 'Summary Only')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='emotion_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='emotion_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='keypoints',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='summary',
            name='type',
            field=models.CharField(choices=[('full', 'Full'), ('short', 'Short'), ('archive', 'Archive')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='summary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SessionArchiveJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='archive_job', to='api.session')),
            ],
            options={
                'db_table': 'session_archive_job',
                'ordering': ['status', '-scheduled_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence__isnull', False)), fields=('session', 'sequence'), name='unique_message_sequence_per_session'),
        ),
    ]
