from django.urls import path
from . import views

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("check-email/", views.check_email, name="check_email"),
    path("send-otp/", views.send_otp, name="send_otp"),
    path("verify-otp/", views.verify_otp, name="verify_otp"),
    path("chat/", views.chat_message, name="chat_message"),
    path("chat/stream/", views.chat_message_stream, name="chat_message_stream"),
    path("voice/process/", views.voice_process, name="voice_process"),
    path("voice/welcome-audio/", views.voice_welcome_audio, name="voice_welcome_audio"),
    path("chat/welcome/", views.chat_welcome, name="chat_welcome"),
    path("chat/summary/", views.chat_summary, name="chat_summary"),
    path("sessions/count/", views.get_session_count, name="get_session_count"),
    path("sessions/save/", views.save_session, name="save_session"),
    path("sessions/recent/", views.get_recent_sessions, name="get_recent_sessions"),
    path("sessions/get/", views.get_session_by_id, name="get_session_by_id"),
    path("sessions/star/", views.toggle_session_star, name="toggle_session_star"),
    path("profile/get/", views.get_user_profile, name="get_user_profile"),
    path("profile/update/", views.update_user_profile, name="update_user_profile"),
    path("users/dashboard-tour/", views.update_dashboard_tour, name="update_dashboard_tour"),
    path("stt/transcribe/", views.stt_transcribe, name="stt_transcribe"),
    path("stt/transcribe-partial/", views.stt_transcribe_partial, name="stt_transcribe_partial"),
    path("tts/synthesize/", views.tts_synthesize, name="tts_synthesize"),
    path("diagnostic-tests/status/", views.diagnostic_test_status, name="diagnostic_test_status"),
    path("diagnostic-tests/submit/", views.diagnostic_test_submit, name="diagnostic_test_submit"),
    path("diagnostic-tests/history/", views.diagnostic_test_history, name="diagnostic_test_history"),
    path("diagnostic-tests/mood-trend/", views.diagnostic_test_mood_trend, name="diagnostic_test_mood_trend"),
    path("diagnostic-tests/streak/", views.diagnostic_test_streak, name="diagnostic_test_streak"),
    path("therapists/", views.get_therapists, name="get_therapists"),
]
